name: Style

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
      
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "**/*.cpp **/*.h **/*.hpp"